XGBoost:
  n_estimators: 401
  eta : 0.005
  max_depth : 4
  reg_alpha: 0.03
  eval_metric: "aucpr"
  subsample: 0.5
  colsample_bytree: 0.5
  gamma : 5
  learning_rate: 0.05
  scale_pos_weight: 1.5

KPrototypes:
  N_CLUSTERS: 3 

AUCROC: 
  THRESHOLD: 0.4