COLUMNS:
  customerID: object
  gender: object
  SeniorCitizen: object
  Partner: object
  Dependents: object
  tenure: int64
  PhoneService: object
  MultipleLines: object
  InternetService: object
  OnlineSecurity: object
  OnlineBackup: object
  DeviceProtection: object
  TechSupport: object
  StreamingTV: object
  StreamingMovies: object
  Contract  : object
  PaperlessBilling: object
  PaymentMethod: object
  MonthlyCharges: float64
  TotalCharges: float64  
  Churn: object

TARGET_COLUMN:
  target_1: Ordinal__Churn
