name: Workflow

on:
  push:
    branches:
      - main
    paths:
      - config/**
      - src/**
      - data/*
      - .github/workflow/dvc_pipeline.yaml


jobs: 
  Integration: 
    name: Continous Integration
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"


  RunCode:
    name: Running the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2

      - name: install dvc
        run: pip install dvc

      - name: Pull data from DVC
        run:
          dvc remote add origin https://dagshub.com/FBrownp/ml-churn.dvc
          dvc remote default origin
          dvc remote modify origin --local auth basic 
          dvc remote modify origin --local user FBrownp 
          dvc remote modify origin --local password ${{secrets.DAGSHUBKEY}}
          dvc pull
          

      - name: Run DVC
        run: dvc repro
  # Deploy:
  #   name: deploy to docker images
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@main
  #   - name: build and push to docker
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{secrets.DOCKER_USERNAME}}
  #       password: ${{secrets.DOCKER_PASSWORD}}
  #       repository: ${{github.repository}}
  #       tag_with_ref: true
  #       tag_with_sha: true
  #       tags: ${{github.sha}}
      