name: Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - 'template.py'
      - 'setup.py'
      - 'artifacts'
      - 'research'
      - 'app.py'
      - 'main.py'
      - '.gitattributes'
      - 'mlruns/0'

env:
  DAGSHUGKEY: ${{secrets.DAGSHUBKEY}}
  GITHUBKEY: ${{secrets.SECRET_ENV}}

jobs: 
  Integration: 
    name: Continous Integration
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"


  RunCode:
    name: Running the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2


      - name: Docker login
        run : echo "${{ secrets.SECRET_ENV }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Packages
      #   run: pip install -r requirements.txt

      # - name: Upgrade cryptography package
      #   run: pip3 install --upgrade cryptography==38.0.4


      - name: Pull data from DVC
        run: |
         docker run -v $(pwd):/app -e DAGSHUGKEY=${DAGSHUGKEY} ghcr.io/fbrownp/ml-churn:latest /bin/bash -c "
          dvc remote default origin-s3
          dvc remote modify origin-s3 --local access_key_id ${{secrets.DAGSHUBKEY}}
          dvc remote modify origin-s3 --local secret_access_key ${{secrets.DAGSHUBKEY}}
          dvc pull
          dvc repro
          dvc push -r origin-s3
          "


      # - name: Connect to repo
      #   run:
      #     dvc remote default origin-s3
      
      # - name: User
      #   run:
      #     dvc remote modify origin-s3 --local access_key_id ${{secrets.DAGSHUBKEY}}
      
      # - name: Password
      #   run:
      #     dvc remote modify origin-s3 --local secret_access_key ${{secrets.DAGSHUBKEY}}

      # - name: Run DVC
      #   run: dvc repro



      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v4 
        with:
          commit_message: Commit changes in dvc.lock
          branch: main
          file-pattern: dvc.lock

      - name: Push MLruns to Github
        run: |
          git config --global user.email "fbrownp@gmail.com" && \
            git config --global user.name "fbrownp" && \
            git config --global credential.helper store && \
            echo GITHUBKEY > ~/.git-credentials
            cd ml-churn

            git add mlruns
            git commit -m "mlruns add"
            git push



  # Deploy:
  #   name: deploy to docker images
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@main
  #   - name: build and push to docker
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{secrets.DOCKER_USERNAME}}
  #       password: ${{secrets.DOCKER_PASSWORD}}
  #       repository: ${{github.repository}}
  #       tag_with_ref: true
  #       tag_with_sha: true
  #       tags: ${{github.sha}}
      